services:
  db:
    image: postgres:13
    container_name: ${CONTAINER_NAME}_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network_name
    restart: unless-stopped
    cpus: 0.2
    mem_limit: 128m

  web:
    build: .
    container_name: ${CONTAINER_NAME}_web
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - network_name
    restart: unless-stopped
    cpus: 0.25
    mem_limit: 512m

  bot:
    build: .
    container_name: ${CONTAINER_NAME}_bot
    command: >
      sh -c "python bot/tg_bot.py & 
             sleep 40 && 
             python run_check_subscriptions.py"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - network_name
    restart: unless-stopped
    cpus: 0.4

networks:
  network_name:
    external: false
    name: ${NETWORK_NAME}

volumes:
  postgres_data:
